EquipoA:
    Nombre: "Fiuba"
    Color: "Verde"
    Formacion: "3-1-2"
EquipoB:
    Nombre: "UTN"
    Color: "Rojo"
    Formacion: "3-2-1"
LogLevel: "info"
MaxJugadores: "2"
usuarios:
-
    -messi
    -barsa
-
    -maradona
    -napoli
-
    -roman
    -boca
-
    -lincha
    -racing
-
    -pipi
    -sanlore
-
    -crespo
    -river
-
